var login_text_arr = ['Email: ','Password: ','Remember me '],
    lang_accept = "CONFIRM",
    lang_cancel = "CANCEL",
    search_button_close = "Close",
    auth_btn_ok = 'Authorization',
    auth_btn_cansel = 'Login',
    hello = 'Hello',
    lang_auth_request = 'Please login',
    auth_fail = 'Authorization error',
    auth_done = 'Successful login',
    change_account = 'Switch User',
    lang_favourite = 'FAVORITE',
    lang_recommended = 'RECOMMEND',
    lang_main_menu_settings = 'SETTINGS',
    lang_serv_auth = 'ACCOUNT',
    lang_serv_quality = 'DESIRABLE QUALITIES',
    lang_main_menu_search = 'SEARCH',
    auth_btn_enter = 'LOGIN',
    auth_btn_logout = 'LOGOUT',
    lang_extSubCatLst_counter= ' from ',
    lang_no_comments = 'there is no comments for this film',
    lang_from_favourites = 'From favourites',
    lang_to_favourites = 'Add to favourites',
    lang_multiply = 's',
    exit_confirm_mes = 'Are you sure want to exit?',
    lang_login = 'Enter login',
    lang_password = 'Enter password',
    lang_zero_search_rezult = 'film was not found',
    lang_zero_genre_films_total_num = 'There is no video files at this genre',
    lang_marks = 'Marks',
    lang_already_voted = 'You have already voted',
    lang_like="Liked",
    lang_director="Director: ",
    lang_genre="Genre: ",
    lang_rating="Rating: ",
    lang_budget="Budget",
    lang_kinopoisk="Kinopoisk: ",
    lang_menu_play="Play video",
    lang_series_0="play",
    lang_series_1="season 0, series 0",
    lang_series_2="quality selection",
    lang_series_3="play from the begining",
    lang_series_list='List of series',
    lang_auth_error='Authorization error',
    lang_button_close = "Close",
    lang_loading_message = "Loading data...",
    lang_message_server_down = "Server connection error",
    lang_message_server_no_ansver = "No response from server",
    lang_minutes_movie_info = " minutes",
    lang_hours_movie_info = " h. ",
    lang_genre_name_all = "All",
    director_id="Director:",
    lang_video_quality_list = ['Automatic', 'Best (1080p)', 'High (720p)', 'Clear (576p)', 'Good (480p)', 'Normal (360r)', 'Mean (320r)', 'Low (240r)'],
    lang_comments_month = {'01':'Jan', '02':'Feb', '03':'Mar', '04':'Apr', '05':'May', '06':'Jun' , '07':'Jul', '08':'Aug', '09':'Sep', '10':'Oct', '11':'Nov', '12':'Dec'}
    ;

var langs = {
    lang_footer_keyboard: "Keyboard",
    cat_0: "RECOMMEND",
    modal_auth_info1: "To authorize the use registration data from the site www.megogo.net",
    modal_auth_info2: "To authorize the use registration data from the site www.megogo.net",
    modal_login1:"Login:",
    modal_pass1:"Password:",
    modal_login2:"Login:",
    modal_pass2:"Password:",  
    exit_confirm_mes: "Are you sure want to exit?",
    info_0:"play film",
    info_1:"actors",
    info_2:"similar movies",
    info_3:"Add to favourites",
    info_4:"reviews",
    info_5:"rate",
    info_6:"Choose quality",    
    lang_like:"Liked",
    lang_dont_like:"Do not like",
    lang_player_hide:"Hide",
    lang_searching:"Search:",
    lang_serv_menu1:"Account",
    lang_serv_menu2:"Child Protection",
    lang_footer_return:"Back",
    lang_footer_exit:"Exit",
    sort_new:"new",
    sort_rating:"by ratings",
    sort_popular:"popular",
    sort_year:"by year",
    lang_search_main_menu:"SEARCH",
    lang_service_main_menu:"SETTINGS",
    director_id:"Director :",
    lang_footer_pageup:"Up",
    lang_footer_pagedown:"Down"
}
