var login_text_arr = ['Email: ','Пароль: ','Запомнить '],
    lang_accept = "ПОДТВЕРДИТЬ",
    lang_cancel = "ОТМЕНА",
    search_button_close = "Закрыть",
    auth_btn_ok = 'Авторизация',
    auth_btn_cansel = 'Войти',
    hello = 'Здравствуйте',
    lang_auth_request = 'Пожалуйста, авторизируйтесь',
    auth_fail = 'Ошибка авторизации',
    auth_done = 'Успешная авторизация',
    change_account = 'Сменить пользователя',
    lang_favourite = 'ИЗБРАННОЕ',
    lang_recommended = 'РЕКОМЕНДУЕМ',
    lang_main_menu_settings = 'НАСТРОЙКИ',
    lang_serv_auth = 'УЧЕТНАЯ ЗАПИСЬ',
    lang_serv_quality = 'ЖЕЛАЕМОЕ КАЧЕСТВО',
    lang_main_menu_search = 'ПОИСК',
    auth_btn_enter = 'ВОЙТИ',
    auth_btn_logout = 'ВЫЙТИ',
    lang_extSubCatLst_counter= ' из ',
    lang_no_comments = 'У этого фильма нет ни одного комментария',
    lang_from_favourites = 'Из избранного',
    lang_to_favourites = 'В избранное',
    lang_multiply = 'ы',
    exit_confirm_mes = 'Подтверждаете выход?',
    lang_login = 'Введите логин',
    lang_password = 'Введите пароль',
    lang_zero_search_rezult = 'Фильм не найден',
    lang_zero_genre_films_total_num = 'В данном жанре пока нет видоезаписей',
    lang_marks = 'Оценки',
    lang_already_voted = 'Вы уже голосовали',
    lang_like="Понравилось",
    lang_director="Режиссер :",
    lang_genre="Жанр: ",
    lang_rating="Рейтинг: ",
    lang_budget="Бюджет",
    lang_kinopoisk="Кинопоиск: ",
    lang_menu_play="Cмотреть фильм",
    lang_series_0="воспроизвести",
    lang_series_1="сезон 12, серия 24",
    lang_series_2="выбор качества",
    lang_series_3="смотреть сначала",
    lang_series_list='Список серий',
    lang_auth_error='Ошибка авторизации',
    lang_button_close = "Закрыть",
    lang_loading_message = "Загрузка данных...",
    lang_message_server_down = "Ошибка связи с сервером",
    lang_message_server_no_ansver = "Нет ответа от сервера",
    lang_minutes_movie_info = " мин.",
    lang_hours_movie_info = " ч. ",
    lang_genre_name_all = "Все",
    lang_genre="Жанр:" ,
    lang_rating="Рейтинг: ",
    director_id="Режиссер:",
    lang_video_quality_list = ['Автоматическое','Наилучшее (1080р)','Высокое (720р)','Чёткое (576р)','Хорошее (480р)','Обычное (360р)','Среднее (320р)','Низкое (240р)'],
    lang_comments_month = {'01':'янв', '02':'фев', '03':'март', '04':'апр', '05':'май', '06':'июнь', '07':'июль','08':'авг','09':'сент','10':'окт','11':'ноя','12':'дек'}
    ;

var langs = {
    lang_footer_keyboard: "Клавиатура",
    cat_0: "РЕКОМЕНДУЕМ",
    modal_auth_info1: "Для авторизации используйте регистрационные данные с сайта www.megogo.net",
    modal_auth_info2: "Для авторизации используйте регистрационные данные с сайта www.megogo.net",
    modal_login1:"Логин:",
    modal_pass1:"Пароль:",
    modal_login2:"Логин:",
    modal_pass2:"Пароль:",  
    exit_confirm_mes: "Подтверждаете выход?",
    info_0:"смотреть фильм",
    info_1:"актеры",
    info_2:"похожие фильмы",
    info_3:"В избранное",
    info_4:"отзывы",
    info_5:"оценить фильм",
    info_6:"Выбрать качество",    
    lang_like:"Понравилось",
    lang_dont_like:"Не понравилось",
    lang_player_hide:"Скрыть",
    lang_searching:"Искать:",
    lang_serv_menu1:"Учетная запись",
    lang_serv_menu2:"Защита от детей",
    lang_footer_return:"Назад",
    lang_footer_exit:"Выйти",
    sort_new:"новые",
    sort_rating:"по рейтингу",
    sort_popular:"популярные",
    sort_year:"по году",
    lang_search_main_menu:"ПОИСК",
    lang_service_main_menu:"НАСТРОЙКИ",
    director_id:"Режиссер :",
    lang_footer_pageup:"Вверх",
    lang_footer_pagedown:"Вниз"
}
